# Generated by Django 3.2.8 on 2021-10-22 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20211022_0352'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scop',
            new_name='Scope',
        ),
    ]
