# Generated by Django 3.2.8 on 2021-11-05 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_measurement_nullable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='nullable',
            new_name='nullable_image',
        ),
    ]
